<!doctype html>
<html>
    <head>
        <title>Nested scroll test</title>
        <style media="screen">
            html,
            body {
                margin: 0;
            }

            body {
                background: green;
            }

            html,
            body,
            .content-container {
                height: 100%;
                width: 100%;
            }

            iframe {
                border: 0;
                /*
                height is completely destroyed by Apple's excuse for a browser, but you need to set
                this to achieve the 'same' result in proper browsers. It will be the iframe that
                scrolls rather than the content-container but it will look the same.
                */
                height: 100%;
                width: 100%;
            }

            .content-container {
                position: relative;
                -webkit-overflow-scrolling: touch;
                overflow: auto;
                font-size: 1px;
            }
        </style>
    </head>
    <body>
        <div class="content-container">

            <button id="boom" type="button">Change</button>
            <script>
                document.getElementById('boom').onclick = function () {
                    document.getElementById('shit').src = 'replace.phtml';
                };
            </script>

            <iframe id="shit" name="shit"></iframe>

            <script>
                document.getElementById('shit').src = 'content.phtml';
            </script>
        </div>
    </body>
</html>
