<!doctype html>
<html>
    <head>
        <title>Nested scroll test</title>
    </head>
    <style media="screen">
        html,
        body {
            margin: 0;
        }

        body {
            background: red;
        }

        html,
        body,
        .content-container,
        iframe {
            height: 100%;
            width: 100%;
        }

        .content-container {
            position: relative;
        }
    </style>
    <body>
        <div class="content-container">
            <iframe src="nested-iframe1.phtml"></iframe>
        </div>
    </body>
</html>
