<!doctype html>
<html>
    <head>
        <title>Nested iframe 2:: scroll test</title>
        <style media="screen">
            html,
            body {
                margin: 0;
            }

            body {
                background: pink;
            }

            html,
            body,
            .content-container,
            iframe {
                height: 100%;
                width: 100%;
            }

            iframe {
                border: 0;
            }

            .content-container {
                position: relative;
                -webkit-overflow-scrolling: touch;
                overflow: auto;
                font-size: 1px;
                
            }
        </style>
    </head>
    <body>
        <div class="content-container">
            <iframe src="content-iframe.phtml"></iframe>
        </div>
    </body>
</html>
